name: Documentation site

on:
  pull_request:
    paths: ['docs-web/**', '.github/workflows/docs-web*.yml']
  push:
    paths: ['docs-web/**', '.github/workflows/docs-web*.yml']

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: docs-web
    steps:
      - uses: actions/checkout@v7.0.1
      - uses: pnpm/action-setup@v6.1.0
        with:
          package_json_file: docs-web/package.json
      - uses: actions/setup-node@v7.0.0
        with:
          node-version: 24
          cache: pnpm
          cache-dependency-path: docs-web/pnpm-lock.yaml
      - run: pnpm install --frozen-lockfile
      - run: pnpm check
      - run: pnpm build
